mod auto_config;
mod capabilities;
mod catalog_state;
mod cognitive_runtime;
mod config;
mod context_mode;
mod mcp;
mod memory;
mod progressive_memory;
mod provider;
mod runtime;
mod runtime_paths;
mod skill_router;
mod task_manager;
mod update;

pub use auto_config::AutoConfigIntent;
pub use auto_config::AutoConfigResult;
pub use auto_config::apply_auto_config;
pub use auto_config::detect_auto_config;
pub use auto_config::update_installed_skill;
pub use capabilities::*;
pub use catalog_state::ConfiguredMcp;
pub use catalog_state::InstalledSkill;
pub use catalog_state::list_configured_mcp;
pub use catalog_state::list_installed_skills;
pub use catalog_state::remove_configured_mcp;
pub use catalog_state::remove_installed_skill;
pub use catalog_state::set_mcp_enabled;
pub use catalog_state::set_skill_enabled;
pub use cognitive_runtime::*;
pub use config::ModelChoice;
pub use config::ProviderConfig;
pub use config::ProviderDocument;
pub use config::ProviderKind;
pub use config::ProviderRegistry;
pub use config::ProviderSettings;
pub use config::RemoteCompactionMode;
pub use context_mode::ContextMode;
pub use context_mode::classify_context_mode;
pub use mcp::McpRuntime;
pub use mcp::McpServerStatus;
pub use memory::Memory;
pub use memory::MemoryLifecycle;
pub use memory::MemoryManager;
pub use memory::MemoryScope;
pub use memory::MemoryType;
pub use progressive_memory::ProgressiveAppendResult;
pub use progressive_memory::ProgressiveMemoryStore;
pub use provider::HttpModelProvider;
pub use runtime::*;
pub use runtime_paths::*;
pub use skill_router::*;
pub use task_manager::*;
pub use update::UpdateCheckResult;
pub use update::check_for_update;
